[project]
name = "midaug-mcp-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "fastmcp>=2.13.1",
    "requests>=2.32.5",
    "zhdate>=0.1.0",
]

[project.scripts]
midaug-mcp-tools = "mcp_server.main:app"

[[tool.uv.index]]
url = "https://mirrors.aliyun.com/pypi/simple/"
default = true

[[tool.uv.index]]
url = "https://mirrors.cloud.tencent.com/pypi/simple/"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"

[[tool.uv.index]]
url = "https://pypi.mirrors.ustc.edu.cn/simple/"
